### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew.cluster#8]
@mschubert, your template files at https://github.com/mschubert/clustermq/tree/master/inst were extremely helpful for developing all of `crew.cluster`. I attributed you in the [`NOTICE`](https://github.com/wlandau/crew.cluster/blob/main/NOTICE) file, the [README](https://github.com/wlandau/crew.cluster/blob/main/README.md#thanks), and in a [documentation section](https://github.com/wlandau/crew.cluster/blob/3e8d0d74685f8f7d9005e65327ecdb0386258261/R/crew_package.R#L21-L29) which is [inherited](https://github.com/wlandau/crew.cluster/blob/3e8d0d74685f8f7d9005e65327ecdb0386258261/R/crew_controller_slurm.R#L11) throughout the package. Are there any additions or modifications you you would like me to make to these references?

And once again, many thanks for developing `clustermq`. My colleagues use it all the time on our SGE cluster. And I doubt the `crew` ecosystem will conflict with `clustermq` because the latter is a much better fit for SIMD workflows.

**Comment by mschubert** [comment]
You are very welcome. As far as I'm concerned, the template files are not copyright-able because they're just a list of documented scheduler parameters. So the license notice is not required. But it's nice that you mention where you took inspiration from.

Good luck with your `crew` approach to `targets`!

**Comment by wlandau** [comment]
Thanks for the encouragement!
